version: "2.2"

services:
    bikestore-mongo:
        image: mongo:4.2.0
        expose:
            - 27017
        healthcheck:
            test: "mongo --quiet 'localhost/test' --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"
            interval: 5s
            timeout: 3s
            retries: 30
        networks:
            - bikestore-network
    bikestore-app:
        depends_on:
            bikestore-mongo:
                condition: service_healthy
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        environment:
            - APP_PORT=3000
            - MONGO_URL=mongodb://bikestore-mongo:27017
            - MONGO_DOCUMENT=bikestore
        expose:
            - 3000
        ports:
            - 3000:3000
        networks:
            - bikestore-network
networks:
    bikestore-network:
